export const DEFAULT_REALM_STACK_META_REALM_PATH: string =
  'REALM_STACK_META_REALM_PATH.path';
export const DEFAULT_REALM_STACK_LOADABLE_REALM_PATH: string =
  'SIDEWAYS_STACKS.path';

export const DEFAULT_REALM_GRAPH_META_REALM_PATH: string =
  'REALM_GRAPH_META_REALM_PATH.path';
export const DEFAULT_REALM_GRAPH_LOADABLE_REALM_PATH: string =
  'SIDEWAYS_GRAPHS.path';
