export const DEFAULT_REALM_JSON_META_REALM_PATH: string =
  'REALM_JSON_META_REALM_PATH.path';
export const DEFAULT_REALM_JSON_LOADABLE_REALM_PATH: string =
  'SIDEWAYS_JSON.path';

import {DECORATION_ROW_KEY} from 'ssDatabase/api/types';

export const DEFAULT_REALM_JSON_COLLECTION_NAME = 'user_json';
export const DEFAULT_REALM_JSON_OUTPUT_ROW_NAME = DECORATION_ROW_KEY.OUTPUT;
export const DEFAULT_REALM_JSON_INPUT_ROW_NAME = DECORATION_ROW_KEY.INPUT;
