export const DEFAULT_REALM_JSON_META_REALM_PATH: string =
  'REALM_JSON_META_REALM_PATH.path';
export const DEFAULT_REALM_JSON_LOADABLE_REALM_PATH: string =
  'SIDEWAYS_JSON.path';

export const DEFAULT_REALM_JSON_COLLECTION_NAME = 'user_json';
